### ISSUE TITLE
`children` routes are not working

### ISSUE THREAD

**Issue by sibbng** [fabiospampinato/voby-simple-router#1]
Hi, it seems children routes are not working at all. I tested both static and dynamic routes but no luck. Defining at top level works.

Reproduction: https://stackblitz.com/edit/vitejs-vite-ms9fna?file=src/main.tsx

**Comment by fabiospampinato** [comment]
It should be fixed in v1.4.1, thanks 👍 I had two lines in the wrong order here:

https://github.com/fabiospampinato/voby-simple-router/blob/9b91a59c300457f5312da4c5275e19f706c25f6d/src/hooks/use_router.ts#L23-L25

**Comment by sibbng** [comment]
Thanks for quick fix 🙏
